<a href="https://colab.research.google.com/github/wojtek840919/data-science-bootcamp/blob/main/01_wprowadzenie/01_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print ('Hello Colab')

Hello Colab


shift+enter -uruchamianie kodu

# Array

In [2]:
import numpy as np
np.__version__
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_CopyMode', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__getattr__', '__git_version__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_distributor_in

In [ ]:
help(np.array)

In [ ]:
x = np.array([1, 3])
x

array([1, 3])

In [ ]:
print(x)

[1 3]


In [ ]:
  x.ndim

1

In [ ]:
x.size

2

In [ ]:
x.dtype

dtype('int64')

In [ ]:
x.shape

(2,)

In [ ]:
x = np.array([2.3, 3.4, 5.6])
x

array([2.3, 3.4, 5.6])

In [ ]:
x.dtype

dtype('float64')

In [ ]:
x.shape

(3,)

In [ ]:
x.size

3

In [ ]:
x.ndim

1

In [ ]:
x =np.array([[2,3,5], [4,5,6]])
x

NameError: ignored

In [ ]:
print(x)

[[2 3 5]
 [4 5 6]]


In [ ]:
A = np.array([1.0, 2.3, 4.5], dtype = 'int')
A

array([1, 2, 4])

In [ ]:
A.dtype

dtype('int64')

In [ ]:
np.zeros(shape=(4, 10), dtype='int')

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [ ]:
np.ones(shape=(5,5), dtype='int')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
np.full(shape=(3, 3), fill_value=4, dtype='int') 

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
range(10)

range(0, 10)

In [ ]:
np.arange(start=5, stop=25, step=5)

array([ 5, 10, 15, 20])

In [ ]:
np.linspace(start=10, stop=100, num=10, dtype='int')

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [ ]:
A = np.arange(15)
A 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
A.reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
print(A.reshape(-1,3))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [ ]:
X = np.array([[1,3], [-2,0]])
X

array([[ 1,  3],
       [-2,  0]])

In [ ]:
Y=np.array([[6,0], [-1,2]])

In [ ]:
print(X)

NameError: ignored

In [ ]:
x =np.array([[2,3,5], [4,5,6]])
x

NameError: ignored

In [ ]:
x = np.array([[2,3], [4,5]])
y = np.array([[2,2], [4,6]])
print(x)
print(y)
x*y

[[2 3]
 [4 5]]
[[2 2]
 [4 6]]


array([[ 4,  6],
       [16, 30]])

In [ ]:
np.dot(x,y)

array([[16, 22],
       [28, 38]])

In [ ]:
x.dot(y)

array([[16, 22],
       [28, 38]])

In [ ]:
y.dot(x)

array([[12, 16],
       [32, 42]])

In [ ]:
x @ y

array([[16, 22],
       [28, 38]])

In [ ]:
np.random.seed(0)

In [ ]:
np.random.randn(10,2)

array([[ 1.16184901, -1.41347945],
       [ 0.95458546, -0.6977105 ],
       [-0.2829066 ,  0.065417  ],
       [-0.10370335,  0.27308507],
       [ 0.87534326, -1.30732215],
       [-0.51992126,  0.43889066],
       [ 0.5913255 , -1.16836485],
       [-0.52192401, -0.31784156],
       [-0.25462839, -0.91852187],
       [ 1.34119784, -0.06733119]])

In [ ]:
np.random.randint(low=100, high=200)

186

In [ ]:
np.random.choice([4,6,8])

6

In [4]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.random.shuffle(data)
data

array([6, 7, 0, 8, 2, 3, 9, 5, 4, 1])

In [ ]:
data

array([6, 7, 0, 8, 2, 3, 9, 5, 4, 1])

In [ ]:
np.exp(1)

NameError: ignored

In [6]:
np.random.shuffle(data)
data

array([2, 4, 3, 5, 7, 9, 8, 1, 6, 0])

In [7]:
data[3:]

array([5, 7, 9, 8, 1, 6, 0])

In [8]:
data[:5]

array([2, 4, 3, 5, 7])

In [12]:
data[:5].reshape(1,5)

array([[2, 4, 3, 5, 7]])

In [13]:
data[:5].reshape(5,1)

array([[2],
       [4],
       [3],
       [5],
       [7]])

In [18]:
A = np.arange(0,20)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [19]:
A = A.reshape(4,5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [20]:
  A[0]

array([0, 1, 2, 3, 4])

In [21]:
A[:, 0]

array([ 0,  5, 10, 15])

In [22]:
A[1,1]

6

In [24]:
A[1:3, 1:4]

array([[ 6,  7,  8],
       [11, 12, 13]])

In [25]:
A[1,2] =15
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 15,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [29]:
for row in A:
  print(row[0])

0
5
10
15


In [30]:
for item in A.flat:
  print(item)

0
1
2
3
4
5
6
15
8
9
10
11
12
13
14
15
16
17
18
19


In [31]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 15,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [32]:
A.shape

(4, 5)

In [34]:
A.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6, 15],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [38]:
A.ravel()

array([ 0,  1,  2,  3,  4,  5,  6, 15,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [39]:
A.T

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2, 15, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

In [47]:
A = np.arange(-10,10, 0.5)
A = A.reshape(10, -1)
A

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [48]:
A>0

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [49]:
A[A>0]

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])

In [50]:
np.bitwise_and(A> -5, A<5)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [51]:
 A[np.bitwise_and(A> -5, A<5)]

array([-4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,
        1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])