<a href="https://colab.research.google.com/github/wojtek840919/data-science-bootcamp/blob/main/01_wprowadzenie/02_algebra_liniowa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np


In [7]:
v1= np.array([-1,4])
v1

array([-1,  4])

In [8]:
np.linalg.norm(v1)

4.123105625617661

In [11]:
v2 = np.array([-10,10,13])

In [12]:
np.linalg.norm(v2)

19.209372712298546

In [14]:
  p = np.array([3,0])
  q = np.array([0,4])
  np.linalg.norm(p-q)

5.0

In [15]:
x=np.array([[5,3], [3,9]])
y=np.array([[1], [-1]])
print(x, '\n')
print(y)


[[5 3]
 [3 9]] 

[[ 1]
 [-1]]


In [16]:
Z=np.dot(x,y)
Z

array([[ 2],
       [-6]])

In [17]:
Z.shape

(2, 1)

In [7]:
A = np.array([[2,4], [-1,3]])
round(np.linalg.det(A))

10

In [7]:
np.trace(A)

5

In [8]:
np.eye(5, dtype ='int')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [5]:
A

NameError: ignored

In [11]:
B = np.linalg.inv(A)
B

array([[ 0.3, -0.4],
       [ 0.1,  0.2]])

In [12]:
np.dot(A,B)

array([[1.00000000e+00, 0.00000000e+00],
       [2.77555756e-17, 1.00000000e+00]])

In [13]:
np.set_printoptions(precision=4, suppress=True)

In [8]:
np.transpose(A)

array([[ 2, -1],
       [ 4,  3]])

In [9]:
A

array([[ 2,  4],
       [-1,  3]])

In [10]:
A.T

array([[ 2, -1],
       [ 4,  3]])

In [15]:
A=np.eye(10, dtype='int')

In [16]:
A

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [17]:
A[2,3]

0

In [18]:
A[0,0]

1

In [20]:
A = np.array([[2,4], [1,-1]])
print(A)

[[ 2  4]
 [ 1 -1]]


In [21]:
B = np.array([[10], [-1]])
print(B)

[[10]
 [-1]]


In [22]:
A_inv= np.linalg.inv(A)
X= np.dot(A_inv, B) 

In [23]:
X

array([[1.],
       [2.]])